from datetime import datetime, timedelta

def get_mock_vacantes():
    hoy = datetime.utcnow()

    return [
        # ─── VERDES (reales, recientes) ────────────────────────
        {
            "title": "Backend Developer Junior",
            "company": "Bancolombia",
            "location": "Medellín (Remoto)",
            "salary_min": 3500000,
            "salary_max": 4500000,
            "description": "Buscamos desarrollador backend junior para equipo de pagos digitales. Trabajarás con microservicios en Java Spring Boot y PostgreSQL. Experiencia con APIs REST y Git requerida.",
            "skills_req": ["java", "spring boot", "postgresql", "git", "apis rest"],
            "source": "mock",
            "url": "https://jobs.bancolombia.com/backend-junior-001",
            "posted_at": (hoy - timedelta(days=3)).isoformat(),
            "repost_count": 0,
            "status": "green",
            "hires_youth": True,
        },
        {
            "title": "Desarrollador Backend Junior – Python",
            "company": "Rappi",
            "location": "Bogotá (Híbrido)",
            "salary_min": 4000000,
            "salary_max": 5000000,
            "description": "Únete al equipo de logística de Rappi. Desarrollarás servicios en Python/FastAPI, integración con bases de datos NoSQL y soporte a APIs internas de alto tráfico.",
            "skills_req": ["python", "fastapi", "mongodb", "docker", "git"],
            "source": "mock",
            "url": "https://jobs.rappi.com/backend-python-junior-002",
            "posted_at": (hoy - timedelta(days=5)).isoformat(),
            "repost_count": 0,
            "status": "green",
            "hires_youth": True,
        },
        {
            "title": "Junior Software Engineer – Backend",
            "company": "Tribe",
            "location": "Barranquilla (Presencial)",
            "salary_min": 3000000,
            "salary_max": 3800000,
            "description": "Startup fintech barranquillera busca ingeniero backend junior. Stack: Node.js, Express, MySQL. Ambiente joven, crecimiento rápido y posibilidad de ascenso en 6 meses.",
            "skills_req": ["node.js", "express", "mysql", "javascript", "git"],
            "source": "mock",
            "url": "https://jobs.tribe.co/junior-backend-003",
            "posted_at": (hoy - timedelta(days=7)).isoformat(),
            "repost_count": 0,
            "status": "green",
            "hires_youth": True,
        },
        {
            "title": "Backend Engineer Junior – Java",
            "company": "Seguros Bolívar",
            "location": "Bogotá (Presencial)",
            "salary_min": 3200000,
            "salary_max": 4000000,
            "description": "Área de tecnología busca ingeniero backend para desarrollo de módulos internos. Java 11+, Spring, SQL Server. Se valora experiencia con pruebas unitarias.",
            "skills_req": ["java", "spring", "sql server", "junit", "git"],
            "source": "mock",
            "url": "https://jobs.segurosbolivar.com/backend-junior-004",
            "posted_at": (hoy - timedelta(days=10)).isoformat(),
            "repost_count": 1,
            "status": "green",
            "hires_youth": True,
        },
        {
            "title": "Desarrollador Python Junior",
            "company": "PSL (Pragma)",
            "location": "Medellín (Remoto)",
            "salary_min": 3500000,
            "salary_max": 4200000,
            "description": "Consultora de software busca desarrollador Python para proyectos con clientes en EE.UU. Django, REST APIs, PostgreSQL. Inglés básico deseable.",
            "skills_req": ["python", "django", "postgresql", "apis rest", "inglés"],
            "source": "mock",
            "url": "https://jobs.pragma.com.co/python-junior-005",
            "posted_at": (hoy - timedelta(days=4)).isoformat(),
            "repost_count": 0,
            "status": "green",
            "hires_youth": True,
        },
        {
            "title": "Junior Backend – Node.js",
            "company": "Addi",
            "location": "Bogotá (Remoto)",
            "salary_min": 4500000,
            "salary_max": 5500000,
            "description": "Fintech de crédito en línea busca backend junior. Node.js, TypeScript, PostgreSQL, AWS básico. Equipo 100% remoto y cultura de aprendizaje continuo.",
            "skills_req": ["node.js", "typescript", "postgresql", "aws", "git"],
            "source": "mock",
            "url": "https://jobs.addi.com/backend-node-junior-006",
            "posted_at": (hoy - timedelta(days=2)).isoformat(),
            "repost_count": 0,
            "status": "green",
            "hires_youth": True,
        },
        {
            "title": "Ingeniero de Software Junior",
            "company": "Globant Colombia",
            "location": "Barranquilla (Híbrido)",
            "salary_min": 4000000,
            "salary_max": 5000000,
            "description": "Globant busca ingenieros junior para proyecto con cliente retail en EE.UU. Java o Python, APIs REST, trabajo en equipo ágil. Inglés intermedio requerido.",
            "skills_req": ["java", "python", "apis rest", "scrum", "inglés"],
            "source": "mock",
            "url": "https://jobs.globant.com/software-junior-barranquilla-007",
            "posted_at": (hoy - timedelta(days=6)).isoformat(),
            "repost_count": 0,
            "status": "green",
            "hires_youth": True,
        },
        {
            "title": "Desarrollador Backend Junior – APIs",
            "company": "Totto Digital",
            "location": "Bogotá (Presencial)",
            "salary_min": 2800000,
            "salary_max": 3500000,
            "description": "Equipo de e-commerce busca desarrollador backend para integración de pasarelas de pago y APIs de logística. PHP/Laravel o Python. Primer empleo bienvenido.",
            "skills_req": ["php", "laravel", "mysql", "apis rest", "git"],
            "source": "mock",
            "url": "https://jobs.totto.com/backend-junior-008",
            "posted_at": (hoy - timedelta(days=8)).isoformat(),
            "repost_count": 1,
            "status": "green",
            "hires_youth": True,
        },

        # ─── AMARILLAS (dudosas) ────────────────────────────────
        {
            "title": "Backend Developer Junior",
            "company": "Soluciones Tech SAS",
            "location": "Bogotá (Presencial)",
            "salary_min": 2500000,
            "salary_max": 3000000,
            "description": "Empresa de desarrollo de software busca backend junior con conocimientos en Java, Python o PHP. Experiencia mínima 1 año. Enviar hoja de vida.",
            "skills_req": ["java", "python", "php", "sql"],
            "source": "mock",
            "url": "https://computrabajo.com.co/soluciones-tech-backend-009",
            "posted_at": (hoy - timedelta(days=65)).isoformat(),
            "repost_count": 2,
            "status": "yellow",
            "hires_youth": False,
        },
        {
            "title": "Programador Junior – Múltiples Tecnologías",
            "company": "Inversiones Digitales del Caribe",
            "location": "Barranquilla (Presencial)",
            "salary_min": 1800000,
            "salary_max": 2500000,
            "description": "Se busca programador junior con conocimientos en cualquier lenguaje. Salario a convenir. Buen ambiente laboral. Interesados escribir al WhatsApp.",
            "skills_req": ["programación", "bases de datos"],
            "source": "mock",
            "url": "https://computrabajo.com.co/inversiones-digitales-junior-010",
            "posted_at": (hoy - timedelta(days=80)).isoformat(),
            "repost_count": 3,
            "status": "yellow",
            "hires_youth": False,
        },
        {
            "title": "Desarrollador Web y Backend",
            "company": "Agencia CreaTech",
            "location": "Medellín (Presencial)",
            "salary_min": 2200000,
            "salary_max": 3000000,
            "description": "Agencia creativa busca desarrollador para proyectos web. HTML, CSS, JavaScript, PHP. Posibilidad de contrato por prestación de servicios.",
            "skills_req": ["html", "css", "javascript", "php", "wordpress"],
            "source": "mock",
            "url": "https://elempleo.com/createch-desarrollador-011",
            "posted_at": (hoy - timedelta(days=72)).isoformat(),
            "repost_count": 2,
            "status": "yellow",
            "hires_youth": False,
        },

        # ─── ROJAS (fantasmas) ──────────────────────────────────
        {
            "title": "Ingeniero de Sistemas Junior – Urgente",
            "company": "Consultoría XYZ Colombia",
            "location": "Bogotá / Remoto",
            "salary_min": 2000000,
            "salary_max": 4000000,
            "description": "URGENTE se necesita ingeniero de sistemas para proyecto inmediato. Múltiples vacantes disponibles. Aplica ya. Salario competitivo según experiencia.",
            "skills_req": ["sistemas", "redes", "soporte"],
            "source": "mock",
            "url": "https://computrabajo.com.co/xyz-ingeniero-urgente-012",
            "posted_at": (hoy - timedelta(days=120)).isoformat(),
            "repost_count": 6,
            "status": "red",
            "hires_youth": False,
        },
        {
            "title": "Backend Developer – Proyecto Internacional",
            "company": "Global IT Partners SAS",
            "location": "Remoto (Colombia)",
            "salary_min": 5000000,
            "salary_max": 9000000,
            "description": "Empresa internacional busca desarrolladores backend para proyecto en EE.UU. Salario en dólares. No se requiere experiencia. Aplica ahora, cupos limitados.",
            "skills_req": ["cualquier lenguaje", "inglés"],
            "source": "mock",
            "url": "https://computrabajo.com.co/global-it-backend-013",
            "posted_at": (hoy - timedelta(days=95)).isoformat(),
            "repost_count": 8,
            "status": "red",
            "hires_youth": False,
        },
    ]