/** @type {import('../store/useProfileStore').Job[]} */
export const mockJobs = [
  {
    id: 'mock-job-1',
    titulo: 'Desarrollador Backend Python',
    empresa: 'Sophos Solutions',
    ciudad: 'Barranquilla',
    departamento: 'Atlántico',
    salario_min: 2500000,
    salario_max: 3500000,
    habilidades_requeridas: ['python', 'fastapi', 'postgresql', 'git'],
    sector: 'tecnología',
    experiencia_requerida: 1,
    nivel_educativo_req: 'universitario',
    modalidad: 'hibrido',
    semaforo: 'green',
    descripcion: 'Vacante junior para apoyar APIs con FastAPI en proyectos del Caribe.',
    publicado_at: '2026-05-23T10:00:00Z',
    score_compatibilidad: 84,
    habilidades_match: ['python', 'git'],
    habilidades_faltantes: ['postgresql', 'fastapi'],
    url: 'https://www.linkedin.com/jobs/search/?keywords=python%20backend',
  },
  {
    id: 'mock-job-2',
    titulo: 'Analista de datos junior',
    empresa: 'Grupo Éxito',
    ciudad: 'Barranquilla',
    departamento: 'Atlántico',
    salario_min: 2200000,
    salario_max: 3000000,
    habilidades_requeridas: ['excel', 'python', 'power bi'],
    sector: 'retail',
    experiencia_requerida: 0,
    nivel_educativo_req: 'universitario',
    modalidad: 'presencial',
    semaforo: 'yellow',
    descripcion: 'Primer empleo en analytics para cadena de retail costa norte.',
    publicado_at: '2026-05-22T14:00:00Z',
    score_compatibilidad: 71,
    habilidades_match: ['excel', 'python'],
    habilidades_faltantes: ['power bi'],
    url: 'https://www.linkedin.com/jobs/search/?keywords=analista%20datos',
  },
  {
    id: 'mock-job-3',
    titulo: 'Trainee inversiones',
    empresa: 'OportunidadXM',
    ciudad: 'Remoto',
    salario_min: 5000000,
    salario_max: 5000000,
    habilidades_requeridas: [],
    sector: 'finanzas',
    modalidad: 'remoto',
    semaforo: 'red',
    descripcion: 'Pide pago por capacitación inicial. Vacante bloqueada por DulIA.',
    publicado_at: '2026-05-23T08:00:00Z',
    score_compatibilidad: 0,
    habilidades_match: [],
    habilidades_faltantes: [],
  },
]

/** @type {import('../store/useProfileStore').MarketDashboard} */
export const mockMarket = {
  total_vacantes_activas: 312,
  top_sectores: [
    { sector: 'tecnología', count: 87 },
    { sector: 'comercial', count: 64 },
    { sector: 'logística', count: 41 },
  ],
  salario_promedio: 2800000,
  top_empresas_verdes: ['Bancolombia', 'Rappi', 'Teleperformance'],
  crecimiento_semanal_pct: 12.4,
  ciudad_filtro: 'Barranquilla',
  sector_filtro: null,
  por_modalidad: {
    remoto: 128,
    presencial: 7,
    hibrido: 0,
  },
  por_fuente: {
    getonbrd: 127,
    remotive: 8,
  },
}
